services:
    wallabag_core.twig.extension:
        class: Wallabag\CoreBundle\Twig\Extension\WallabagExtension
        tags:
            - { name: twig.extension }

    # wallabag_core.helper.detect_active_theme:
    #     class: Wallabag\CoreBundle\Helper\DetectActiveTheme
    #     arguments:
    #         - @security.context
    #         - %theme% # default theme from parameters.yml

    # custom form type
    wallabag_core.form.type.config:
        class: Wallabag\CoreBundle\Form\Type\ConfigType
        arguments:
            - %liip_theme.themes%
        tags:
            - { name: form.type, alias: config }

    wallabag_core.form.type.forgot_password:
        class: Wallabag\CoreBundle\Form\Type\ForgotPasswordType
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: forgot_password }

    wallabag_core.param_converter.username_rsstoken_converter:
        class: Wallabag\CoreBundle\ParamConverter\UsernameRssTokenConverter
        tags:
            - { name: request.param_converter, converter: username_rsstoken_converter }
        arguments:
            - @doctrine

    wallabag_core.doctrine.prefixed_naming_strategy:
        class: Wallabag\CoreBundle\Doctrine\Mapping\PrefixedNamingStrategy
        arguments: [%database_table_prefix%]
